
CREATE TABLE useraccount(
    id BIGSERIAL PRIMARY KEY ,
user_name CHARACTER VARYING(16) UNIQUE NOT NULL ,
password CHARACTER VARYING(256) NOT NULL ,
first_name CHARACTER VARYING(16) NOT NULL ,
last_name CHARACTER VARYING(16) NOT NULL ,
status CHARACTER VARYING(10) NOT NULL ,
role CHARACTER VARYING(5) NOT NULL ,
created_at DATE NOT NULL
);