INSERT INTO useraccount (USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME, STATUS, ROLE)
 VALUES ('Admin',
'$2a$10$HRqKxd93EHPgBv7GeKSZGenSPpFTXyRxGsOLWWSjC9Ja.RyWZsdrm',
'Petya','Petrow','ACTIVE','ADMIN');

INSERT INTO useraccount ( USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME, STATUS, ROLE)
 VALUES ('User',
'$2a$10$aW1cTr8NH2fcgvNvJQ1a5..Mz1igR6.Y9WivdY3qhzxP0F3CJS2bW',
'Grisha','Grishut','ACTIVE','USER');

INSERT INTO useraccount ( USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME, STATUS, ROLE)
 VALUES ('Karl',
'$2a$10$DUMcgZUhxPK4QHf4/4tkDuAcPtRMkNqLehIHzd9wknV2ysVJ32Kbq',
'Vanya','Ivanov','ACTIVE','USER');

INSERT INTO useraccount (USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME, STATUS, ROLE)
 VALUES ('Kriss',
'$2a$10$sJfHeo7Fk4Sfbn4nv3Uw8.njNwARfSijXb.sEaJxvjKmpEP6JFmY6',
'Kristina','Petrova','ACTIVE','USER');

INSERT INTO useraccount (USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME, STATUS, ROLE)
 VALUES ('Granta',
'$2a$10$Q4yX01M9ML9K4xRtUKxozuRxo8C1jpLnYSnJi8fPn4NY72ORR.L5u',
'Lesha','Alekseew','ACTIVE','USER');

INSERT INTO useraccount ( USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME, STATUS, ROLE)
 VALUES ('Petroooo',
'$2a$10$TulU9uJrMIJ4TPgt7Pu2peoRW7yrF68n///xl7I/a4XdrydY22kp6',
'Petya','Petrovich','ACTIVE','USER');